### ISSUE TITLE
Bad membernumber causes loop when in Amilia mode

### ISSUE THREAD

**Issue by jschrempp** [makernexus/RFID_System#30] opened 2023-06-16 00:03 UTC
On the Amilia branch. Put a purposely bad client id into the Request Member Information field and tap Request. (I used 57041772)
 
Amilia responds with a 404. 

At this point the Admin station displays "signing into to EZF" and then "timeout getting client info". And then we see the webhook called again every 30 seconds: ezfGetClientByMemberNumber

Obviously EZF responded with something other than a 404 and we need to put that into the web hook.

Jim

**Comment by jschrempp** [comment] 2023-06-16 01:02
I see that the webhook responds with the data "error status 404 from www.amilia.com". 

I see that the admin station displays "Timeout on client info" then "Signing in to EZFacility" and it sends the event ezfClientByMemberNumber again.

The firmware should see this error in the data and stop with a better message on the LCD.

**Comment by jschrempp** [comment] 2023-06-16 01:11
Looking in the code now ...

loopAdmin() state acGetUserInfo calls adminGetUserInfo().

adminGetUserInfo()  state guiWAITFORINFO has a 15 second time out. When that is exceeded we change state to guiCLEANUP.

adminGetUserInfo() state guiCLEANUP sets the local state to guiIDLE and sets the global state to acIDLE. 

At this point the ac state machine should not call adminGetUserInfo again, so the webhook should not be called again. Why is this happening? 

I shut down the android tablet and still saw events firing, so it isn't the table resending commands to the station. 

I also don't see the webhook events coming from the device: 
![image](https://github.com/makernexus/RFID_System/assets/6521097/ae0afa6e-e497-41ab-8948-59d3bacd0817)

I wonder if the Particle Cloud is generating these retries every 30 seconds? When I pulled the plug on the RFID unit then the retries stopped. 
![image](https://github.com/makernexus/RFID_System/assets/6521097/9c7d7327-ab16-41e7-8b3d-1f5fdc35f4e7)

**Comment by BobGlicksman** [comment] 2023-06-16 03:47
Amilia encodes the person ID in the url, resulting in the 404 error because the url won't be found.  EZ facility used clientID as a parameter and not the url itself.  Therefore, EZ Facility accepted the query and returned a suitable result.  This explains the issue -- obviously, it doesn't fix it.

**Comment by BobGlicksman** [comment] 2023-06-23 00:40
After further investigation, there is a problem with the webhook response.  This response filter is set to pass back (to the Argon) legal json consisting of only the json tags that we want.  If we send a non-existent PersonID, what comes back from Amilia (using curl) is:  {"Message":"Person was not found","HttpCode":404,"MoreInformation":null,"TransactionId":"d27bea2f-8381-49a2-90da-311bdcdaf8c9"}.  This is valid json but does not contain any tags that we use.  So I would think that the filter should return an empty json string {} but it does not,  It returns the text "error status 404 from www.amilia.com" **which is not part of the response seen using curl**.  So the webhook itself is picking up the 404 error and bypassing the response filter all together!

Since this latter message (what the Argon receives) is not json, we get a json parsing error which causes the retries and funny LCD messages -- starting at checkinfirmware.ino, line 2321:

    case guiWAITFORINFO:

        if ( g_clientInfo.isValid ) {
            // got client data, let's move on
            guiState = guiFORMATINFO;
            
        } else {
            // timer to limit this state
            if (millis() - processStartMilliseconds > 15000) {
                debugEvent("15 second timer exeeded, get client info error");
                processStartMilliseconds = 0;
                writeToLCD("Timeout clientInfo", "Try Again");
                buzzerBadBeep();
                delay(2000);
                guiState = guiCLEANUP;
            }
        } // Otherwise we stay in this state
        break;

I think that the reason it does not go to guiCLEANUP is becuase we don't timeout -- we get timely responses, but the responses are not json and so we keep retying to get some valid json response.

One solution would be to modify the code to check for this response string (non-json) before trying to json parse it.  Another solution is to see if we can somehow have the webhook return any sort of valid json if this 404 condition occurs.  If we returned some valid (parse-able) json, even without a clientID, we would return with the .isValid flag set true but clientID would be zero (because we clear out the buffer beforehand) and our current test for zero would then return the proper error message that client is not found.

**Comment by BobGlicksman** [comment] 2023-06-23 02:25
Another possible approach to handling the 404 error is to define an errorResponseTopic and subscribe to it.  Presumably, this would allow us to see if the error was a 404 and code an appropriate response in the event handler.  See the Particle documentation:

errorResponseTopic
DEFAULT
hook-error/{{PARTICLE_EVENT_NAME}}

EXAMPLE
"errorResponseTopic": "save_failed_for_{{PARTICLE_DEVICE_ID}}"
Customize the webhook error response event name. Similar to responseTopic.

**Comment by BobGlicksman** [comment] 2023-06-23 04:33
Here is the code that says what we have to do in order to get Member Not Found (line 785):
      } else {
            // xxx this should really be in a common routine with (search deserialize client)
            clearClientInfo();
            JsonObject root_0 = docJSON[0];
            g_clientInfo.clientID = root_0["ClientID"].as<int>();
            if (g_clientInfo.clientID == 0) {
                g_clientInfo.firstName = "Member not found";
                g_clientInfo.isValid = true;

  Whatever solution path is chosen, it must set the firstName to "Member not found" and set isValid to true.  This code will do it if the clientID == 0.  I believe that if any valid json is returned from the query and the json does not have any member info tags in it, then the g_clientInfo struct will be cleared and this existing code will set these values to produce the correct result.

**Comment by BobGlicksman** [comment] 2023-06-23 18:43
I asked the Particle forum about the 404 response and the only suggestion was to configure an process the errorResponseTemplate and process it in firmware.  I think that we can also just test for this specific non-json message and handle it by not calling the json paring process but just setting the g_clientInfo.clientID = 0 and the g_clientInfo.isValid = true.  Then the state machine will handle this properly.  The place where the hook return data is processed into the buffer is around line 888:

void ezfReceiveClientByMemberNumber (const char *event, const char *data)  {
    g_cibmnResponseBuffer = g_cibmnResponseBuffer + String(data);
    debugEvent("clientInfoPart "); // + String(data));    
    clientInfoFromJSONArray(g_cibmnResponseBuffer); // try to parse it
}

Before appending String(data) to the buffer, we can test for the error message and process it per the above.

I tired this (version 2.91) and the result is BETTER, albeit not perfect.  We still get signing into EZFacility  and timeout messages, but but these retires appear to be part of the Particle cloud itself and not what we are doing.  In any event, the app and the firmware do not crash and the admin can proceed to try another member number and if it is types in correctly, the firmware and app will return the correct data (and can make cards, identify cards, etc. OK).  It seems that the Particle cloud itself is doing some retries, as also indicated by one of the responses to my forum posting.

**Comment by BobGlicksman** [comment] 2023-06-23 18:55
I added an errorResponseTemplate to the webhook -- had it respond to the same event as a normal response.  This IMPROVES the situation -- we now get the Member not found status, but we also still get signing in to EZ Facility messages and retires that return the 404 error.  As noted above, this may be a Particle cloud issue over which we don't have much control.  However, the firmware and app do not crash and will respond normally after this error message.  The Particle cloud seems to eventually give up on its retries with the old data.

I won't close this issue yet, but version 2.91 and the updated webhook do seem to help alot.

**Comment by BobGlicksman** [comment] 2023-06-23 19:01
Have pushed version 2.91 firmware and the modified webhook to my GitHub account but not pulled these changes over to MakerNexus at this time, pending review with Jim and a decision as to how to proceed.

**Comment by BobGlicksman** [comment] 2023-06-23 19:08
Here is a reply from Particle about 4xx and 5xx errors:

[Wraithan](https://community.particle.io/u/Wraithan)
Device Cloud Tech Lead
[2h](https://community.particle.io/t/passing-hook-response-with-a-404-http-error/64812/3?u=bobg)
[@gusgonnet](https://community.particle.io/u/gusgonnet)'s reply would let you get the error sometimes, but if you're going to commonly get 404s from the API then you'll run into some issues. We have a karma system on our webhooks that will back off if a server isn't returning 2xx status codes. This is to prevent us from hammering a server that is failing, we rapidly ramp back up once webhooks start succeeding again.

[Webhook reference | Reference | Particle 1](https://docs.particle.io/reference/cloud-apis/webhooks/#limits) talks about this.

With our current system, direct integration with services that return non-2xx status codes as part of regular operation is not recommended, instead you'll need to proxy the request.

**Comment by BobGlicksman** [comment] 2023-06-23 19:39
A link to this forum discussion is here:

https://community.particle.io/t/passing-hook-response-with-a-404-http-error/64812/4

**Comment by BobGlicksman** [comment] 2023-06-24 00:35
I typed in a bad member number and observed the Console event log.  There were several 404 responses followed by what appears to be a re-query followed by more 404 responses followed by a Particle message about slowing down the queries.  This all happened several times until this activity seemed to step.  However, about 1/2 hour later, this behavior started again.  There is nothing in the firmware that could directly explain this behavior, but since Particle is enforcing "karma" by slowing down queries, it is possible that the firmware is sending more frequent and regular queries and we don't see them in the event log.

I then used the admin App to query for a member known to Amilia (no "typo").  I got a proper response but the event log also still showed a few 404 errors (on the old query) but then this stopped and never repeated (tested for almost 2 hours).  It therefore seems that entering a correct member number, which returns valid data (http response code 200) clear out whatever was causing bad queries to repeat.  It seems unlikely that the repeated bad queries are Particle's doing (the slowdowns are Particle's doing).  There must be something in the firmware that isn't getting reset with my fix and causing subsequent re-queries.  This "something" may be related to the subsequent App call to the cloud function that triggers a new query for data by member number.  Calling this function triggers off the query/response to Amila but something must stop it when it is complete.  This "something" perhaps isn't being reset when the query returns a 404 error and so it repeats.  This bears further investigation.

**Comment by BobGlicksman** [comment] 2023-06-24 00:41
Also, when requesting data for a bad member number, the firmware does not return data to the app.  The station shows Member not found but this info is not returned to the app.  The app eventually times out and the request button is enabled, but the process does not complete properly.  If I request a good member number, then things work OK.  So my fix isn't resetting something and this may be the cause of subsequent queries for the bad url.

**Comment by BobGlicksman** [comment] 2023-06-24 19:38
Went through adminGetUserInfo() state machine.  Fron the state machine, it seems like we are getting through state guiFORMATINFO just fine, because Member not found is displayed on the LCD.  So it must go to state guiDISPLAYINGINFO because there are no other paths to go.  The state machine must then go to state guiCLEANUP, either by timeout or because the g_clientInfo.isValid is set.  We don't see a timeout, so the flag is set, as expected (because I forced it to be set on checking the error 404 message).  guiCLEANUP sets the next admin state to acIDLE and the adminGetUserInfo() state to guiIDLE.

When a bad member number has been entered, the firmware seems to be executing guiIDLE next, which is causing retires of the webhook.  But when a valid number is entered, we must be going next to acIDLE waiting for a new command from the app.  Since both of these "next state" values are set in acCLEANUP, something must be different in that the the top level acXXXX state machine is not going back to acIDLE but appears to be staying in acGETUSERINFO (line 2436).  acGETUSERINFO calls adminGetUserInfo() which then begins from the idle state all over again, causing these retries!

So - since the admin state machine is (presumably) setting the ac state machine back to idle, whatever calls loopAdmin() with argument g_adminCommand must not be clearing out the acGETUSERINFO value.  This HAS TO BE related to the Particle.function() call from the app.  Something in the "faked out" return is not causing some flag here to be rest, so adminGetUserInfo() is being called and repeating its loop over and over (and then Particle's "karma" slows everything down).

**Comment by BobGlicksman** [comment] 2023-06-25 17:24
Diagnosed the source of the problem of repeated queries.  App makes repeated calls to app function RequestMemberData.  Normal sequence is to repeatedly call this function.  Return code of 0 means it was called.  Return call of 1 means that an Amilia query is in process.  Return code of 2 means that data is available to read.  The firmware name for this function is queryMember.  With a good member number, the sequence goes 0, 1, 2, ...  With a bad member number, the sequence sticks at 1, causing repeated app calls to this function.  

The function that processes the results to set this return code is cloudQuerymember() - line 1455.  The data (member number) is passed as the argument.  Line 1467 has the test to set the return code to 2 to complete the process:

if ((g_clientInfo.isValid) && (g_clientInfo.memberNumber.startsWith(data)))

So, to fake this out, we must set g_clientInfo.memberNumber to be the number in the functions call.

**Comment by BobGlicksman** [comment] 2023-06-25 18:24
Here is the fix that now returns to the app OK (version 2.93).  However, the Console still shows some repeated queries on the 404 error.

1. Added a global variable at line 183.
2. Put the query member number from the global variable into g_clientInfo.memberNumber so that cloudQueryMember test will pass and set return status to 2.

There are still a few remaining bugs.  (a) we seem to query with bad data 3 times.  Note: there may be more queries; this is what is shown in the Console events.  Good member number only queries once.  (b) tapping CARD INFO after requesting member data (but before burning a card) crashed the app.  Close and reopen the app and it is recovered.  Note:  this bug may have been there before.  This sequence of operations may not have been tested because cards are usually burned after the member query.

**Comment by BobGlicksman** [comment] 2023-06-25 20:39
Looking further at the remaining issues:

(a) query three times -- the event log shows no additional queries from our device, after the first one.  The remaining two queries are shown as "particle internal", so particle must be retrying a few times when there is a hook error.  I will see if the Community can shed more light about this, but it does not seem that we are doing it.

(b) tapping CARD INFO after querying for member but not burning a card -- this is not repeatable and may be the result for trying operations too quickly.  If a wait a little while between operations, everything works OK.  

I think that all of the bugs are now out of version 2.93.  I won't close out this issue until we hold a code and testing review.

**Comment by jschrempp** [comment] 2023-06-25 21:15
Great!JimShrimpware.comJimSchrempp.comSent from my iPhone, that’s my excuse for all the typos. On Jun 25, 2023, at 10:39 PM, Bob Glicksman ***@***.***> wrote:﻿
Looking further at the remaining issues:
(a) query three times -- the event log shows no additional queries from our device, after the first one.  The remaining two queries are shown as "particle internal", so particle must be retrying a few times when there is a hook error.  I will see if the Community can shed more light about this, but it does not seem that we are doing it.
(b) tapping CARD INFO after querying for member but not burning a card -- this is not repeatable and may be the result for trying operations too quickly.  If a wait a little while between operations, everything works OK.
I think that all of the bugs are now out of version 2.93.  I won't close out this issue until we hold a code and testing review.

**Comment by BobGlicksman** [comment] 2023-07-05 21:35
Updated to version 2,94 -- just commented out code that I had tried but didn't work.

This whole issue is closed after review of the changes with Jim.

**Closed as completed by BobGlicksman** 2023-07-05 21:35 UTC
